# Teiko Technical Assessment EDA

In [2]:
import pandas as pd

df = pd.read_csv('cell-count.csv')
df.head(18)

,project,subject,condition,age,sex,treatment,response,sample,sample_type,time_from_treatment_start,b_cell,cd8_t_cell,cd4_t_cell,nk_cell,monocyte
0,prj1,sbj000,melanoma,57,M,miraclib,no,sample00000,PBMC,0,10908,24440,20491,13864,23511
1,prj1,sbj000,melanoma,57,M,miraclib,no,sample00001,PBMC,7,6777,19407,33459,18170,23011
2,prj1,sbj000,melanoma,57,M,miraclib,no,sample00002,PBMC,14,9794,22940,24274,17482,18332
3,prj1,sbj001,carcinoma,68,M,miraclib,yes,sample00003,PBMC,0,10081,20271,36157,14041,12610
4,prj1,sbj001,carcinoma,68,M,miraclib,yes,sample00004,PBMC,7,4372,33778,38293,16527,14933
5,prj1,sbj001,carcinoma,68,M,miraclib,yes,sample00005,PBMC,14,15431,31940,30805,11404,15779
6,prj1,sbj002,melanoma,50,M,miraclib,no,sample00006,PBMC,0,5897,31296,28319,12656,21606
7,prj1,sbj002,melanoma,50,M,miraclib,no,sample00007,PBMC,7,10403,13504,33870,22616,18031
8,prj1,sbj002,melanoma,50,M,miraclib,no,sample00008,PBMC,14,8829,26215,21307,17624,16378
9,prj1,sbj003,melanoma,52,M,miraclib,no,sample00009,PBMC,0,7650,33334,21097,18064,15676
10,prj1,sbj003,melanoma,52,M,miraclib,no,sample00010,PBMC,7,13203,21339,27873,13209,31913
11,prj1,sbj003,melanoma,52,M,miraclib,no,sample00011,PBMC,14,10621,19786,29391,13520,16497
12,prj1,sbj004,carcinoma,77,M,miraclib,yes,sample00012,PBMC,0,14128,21720,40320,14609,18802
13,prj1,sbj004,carcinoma,77,M,miraclib,yes,sample00013,PBMC,7,10681,19994,31697,25043,22073
14,prj1,sbj004,carcinoma,77,M,miraclib,yes,sample00014,PBMC,14,6113,25851,27223,9254,24463
15,prj1,sbj005,carcinoma,60,M,miraclib,no,sample00015,PBMC,0,8261,21523,36217,15753,20937
16,prj1,sbj005,carcinoma,60,M,miraclib,no,sample00016,PBMC,7,7433,22881,33881,9432,22197
17,prj1,sbj005,carcinoma,60,M,miraclib,no,sample00017,PBMC,14,3226,20404,36405,20739,17865

Columns

In [3]:
df.columns

Index(['project', 'subject', 'condition', 'age', 'sex', 'treatment',
       'response', 'sample', 'sample_type', 'time_from_treatment_start',
       'b_cell', 'cd8_t_cell', 'cd4_t_cell', 'nk_cell', 'monocyte'],
      dtype='object')

Shape

In [4]:
df.shape

(10500, 15)

We are going to extract repeated information, by step of 3 each time. so that should be 10500 / 3 rows

In [5]:
df.shape[0] / 3

3500.0

Count how many NAs

In [6]:
df.isna().sum()

project                         0
subject                         0
condition                       0
age                             0
sex                             0
treatment                       0
response                     1422
sample                          0
sample_type                     0
time_from_treatment_start       0
b_cell                          0
cd8_t_cell                      0
cd4_t_cell                      0
nk_cell                         0
monocyte                        0
dtype: int64

In [7]:
df[df['response'].isna()].head(3)

,project,subject,condition,age,sex,treatment,response,sample,sample_type,time_from_treatment_start,b_cell,cd8_t_cell,cd4_t_cell,nk_cell,monocyte
30,prj1,sbj010,healthy,70,M,none,NaN,sample00030,PBMC,0,6413,25167,20437,22317,19638
31,prj1,sbj010,healthy,70,M,none,NaN,sample00031,PBMC,7,7007,30482,31653,14167,23316
32,prj1,sbj010,healthy,70,M,none,NaN,sample00032,PBMC,14,11118,19704,32582,20603,17350

It seems treatments with `'none'` are given a `Nan` `response` value. 
Let's value_counts() the treatments of this subquery.

In [8]:
df[df['response'].isna()][['treatment']].value_counts()

treatment
none         1422
Name: count, dtype: int64

Yes. All are from `none` treatments.

Show NaNs

Types of projects `project`

In [9]:
df[['project']].value_counts()

project
prj1       4500
prj2       3000
prj3       3000
Name: count, dtype: int64

Types of Sample types `sample_type`

In [10]:
df[['sample_type']].value_counts()

sample_type
PBMC           7500
WB             3000
Name: count, dtype: int64

Types of Treatment `treatment` and counts

In [11]:
df[['treatment']].value_counts()

treatment
miraclib     4695
phauximab    4383
none         1422
Name: count, dtype: int64

Types of Conditions `condition` counts

In [12]:
df[['condition']].value_counts()

condition
melanoma     5175
carcinoma    3903
healthy      1422
Name: count, dtype: int64

Ratio of `yes` and `no` responses frmo `response`

In [13]:
df[['response']].value_counts()

response
yes         4611
no          4467
Name: count, dtype: int64

Ratio of `male`/`female` `gender`

In [14]:
df[['sex']].value_counts()

sex
M      5430
F      5070
Name: count, dtype: int64

The `time_from_treatment_start` is always `0`,`7`,`14`

In [15]:
df[['time_from_treatment_start']].value_counts()

time_from_treatment_start
0                            3500
7                            3500
14                           3500
Name: count, dtype: int64

Analyze **how** the drug affects the four(4) *immune cell population* aka, `b_cell`,`cd8_t_cell`,`cd4_t_cell`,`nk_cell`

## Part 1 : Data Management (go to `load_data.py`)

We need three(3) tables:
Subject:
- subject_id
- subject
- condition
- project
- age
- sex

Treatment:
- subject_id
- treatment_id
- treatment
- response 

Sample:
- sample_id
- subject_id
- sample
- sample_type
- time_from_treatment_start
- b_cell
- cd8_t_cell
- cd4_t_cell
- nk_cell
- monocyte

In [16]:
Subject = df[['subject', 'condition', 'project', 'age', 'sex']].iloc[::3]
Subject

       subject  condition project  age sex
0       sbj000   melanoma    prj1   57   M
3       sbj001  carcinoma    prj1   68   M
6       sbj002   melanoma    prj1   50   M
9       sbj003   melanoma    prj1   52   M
12      sbj004  carcinoma    prj1   77   M
...        ...        ...     ...  ...  ..
10485  sbj3495  carcinoma    prj3   74   M
10488  sbj3496  carcinoma    prj3   50   M
10491  sbj3497   melanoma    prj3   71   M
10494  sbj3498   melanoma    prj3   67   M
10497  sbj3499    healthy    prj3   54   M

[3500 rows x 5 columns]

In [17]:
df.head(1)

,project,subject,condition,age,sex,treatment,response,sample,sample_type,time_from_treatment_start,b_cell,cd8_t_cell,cd4_t_cell,nk_cell,monocyte
0,prj1,sbj000,melanoma,57,M,miraclib,no,sample00000,PBMC,0,10908,24440,20491,13864,23511

`Sample` table

still needs the sqlite3 generated `sample_id` INTEGER PRIMARY KEY AUTOINCREMENT and `subject_id` FOREIGN KEY from `Subject` table.

In [18]:
Sample=df[['sample', 'sample_type', 'time_from_treatment_start', 'b_cell', 'cd8_t_cell', 'cd4_t_cell', 'nk_cell', 'monocyte']]
Sample.head(9)

,sample,sample_type,time_from_treatment_start,b_cell,cd8_t_cell,cd4_t_cell,nk_cell,monocyte
0,sample00000,PBMC,0,10908,24440,20491,13864,23511
1,sample00001,PBMC,7,6777,19407,33459,18170,23011
2,sample00002,PBMC,14,9794,22940,24274,17482,18332
3,sample00003,PBMC,0,10081,20271,36157,14041,12610
4,sample00004,PBMC,7,4372,33778,38293,16527,14933
5,sample00005,PBMC,14,15431,31940,30805,11404,15779
6,sample00006,PBMC,0,5897,31296,28319,12656,21606
7,sample00007,PBMC,7,10403,13504,33870,22616,18031
8,sample00008,PBMC,14,8829,26215,21307,17624,16378

In [19]:
Treatment = df[['treatment', 'response']][::3]
Treatment

       treatment response
0       miraclib       no
3       miraclib      yes
6       miraclib       no
9       miraclib       no
12      miraclib      yes
...          ...      ...
10485   miraclib       no
10488  phauximab       no
10491   miraclib      yes
10494  phauximab       no
10497       none      NaN

[3500 rows x 2 columns]

In [ ]:
df[['treatment', 'response']][::3].itt

ValueError: not enough values to unpack (expected 2, got 1)